# Generated by Django 3.1.2 on 2020-10-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='bs_deferred_assets',
        ),
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(max_length=30, null=True, verbose_name='証券コード'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(max_length=30, null=True, verbose_name='業種'),
        ),
    ]
