# Generated by Django 3.1.2 on 2020-10-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20201030_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.IntegerField(null=True, verbose_name='証券コード'),
        ),
    ]
