# Generated by Django 3.1.2 on 2020-10-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20201030_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='fiscal_year',
            field=models.CharField(max_length=30, verbose_name='決算年度'),
        ),
    ]
