# Generated by Django 3.1.2 on 2020-11-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20201030_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='bs_deferred_assets',
            field=models.IntegerField(default=0, verbose_name='繰延資産（百万円）'),
        ),
    ]
